### ISSUE TITLE
[Warning] XSS(Stored) Vulnerabilities in web_chat 1.0.0

### ISSUE THREAD

**Issue by Leeyangee** [jacky-zeng/web_chat#7]
Vulnerability Product:XSS(Stored) Vulnerabilities in web_chat 
Vulnerability version: 1.0.0
Vulnerability type: XSS(Stored)
Vulnerability Details:
Vulnerability location: User Init

after built the project, visit http://chat.zengyanqi.com/touristLogin 
and input the payload:` "><script>alert(document.cookie)</script><li id="` in the name box
![image](https://github.com/jacky-zeng/web_chat/assets/101627018/5a776819-1137-4e2f-8684-d95be9de2d6f)
when other users login , they will see:
<img width="902" alt="image" src="https://github.com/jacky-zeng/web_chat/assets/101627018/6ce2cb09-e208-4463-99c8-a2df9ef53a05">
it proves the payload works, if we need deep information, just modify "alert(document.cookie)" in payload

discoverd by leeya_bug

**Comment by jacky-zeng** [comment]
fixed
